const images = {};

images.importIcon = "/assets/icons/importicon.svg";
images.filterIcon = "/assets/icons/filtericon.svg";
images.shareIcon = "/assets/icons/Share.svg";
images.downloadIcon = "/assets/icons/downloadicon.svg";
images.checkIcon = "/assets/icons/check.svg";
images.dotIcon = "/assets/icons/_Dot.svg";
images.closeIcon = "/assets/icons/close-circle.svg";
images.outlineIcon = "/assets/icons/image-outline.svg";
images.eyeIcon = "/assets/icons/eye1.svg";
images.sendIcon = "/assets/icons/send-2.svg";
images.addIcon = "/assets/icons/add.svg";
images.historyIcon = "/assets/icons/history-broken.svg";
images.documentIcon = "/assets/icons/document.svg";
images.leadColorIcon = "/assets/icons/Color.svg";
images.customerColoricon = "/assets/icons/Color_2.svg";
images.avatar = "/assets/image/Avatar.jpg";
images.searchIcon = "/assets/icons/search-normal.svg";
images.routingIcon= "/assets/icons/routingicon.svg";
images.secondaryaddicon = "/assets/icons/secondaryaddicon.svg";
images.filtericon ="/assets/icons/filtericon.svg"
images.checktickicon="/assets/icons/checktickicon.svg";
images.cancelroundicon = "/assets/icons/cancelroundicon.svg";
images.arrowlefticon = "/assets/icons/arrowlefticon.svg";
images.car = "/assets/icons/car.svg";
images.flame = "/assets/image/flame.png";
images.edit = "/assets/icons/edit.svg";
images.frame = "/assets/icons/frame.svg"
images.closeIconLight = "/assets/images/close-circle.svg";
images.flatDetailsImage = "/assets/image/flat-details-img.jpg"
images.landConfigIcon = "/assets/icons/LandConfigIcon.svg";
images.emojiIcon = "/assets/icons/EmojiIcon.svg";
images.plotConfigIcon = "/assets/icons/PlotConfigIcon.svg";
images.deleteIcon="/assets/icons/deleteicon.svg";
images.eyeIcon = "/assets/icons/eyeicon.svg";
images.tickCircleIcone="/assets/icons/tickcircle.svg"
images.towerImg = "/assets/images/Vector.svg"
images.noDataFound ="/assets/icons/no-data-found.svg"
images.alertTriangle = "/assets/icons/alert-triangle.svg"
images.ellipse = "/assets/icons/Ellipse 14215.svg"
images.editIcon = "/assets/icons/editicon.svg"
images.carIcon = "/assets/icons/car.svg"
images.bikeIcon = "/assets/icons/majesticons_scooter-line.svg"
images.arrowUp = "/assets/images/arrow-up.svg"
images.transferIcon = "/assets/icons/transferIcon.png"
images.file ="/assets/icons/file.svg"
images.parkingIcon = "/assets/icons/ParkingIcon.svg"
images.towerIcon = "/assets/icons/TowerIcon.svg"
images.bankIcon = "/assets/icons/bankAvatar.svg"
images.email ="/assets/icons/email.svg"
images.location="/assets/icons/location_profile.svg"
images.phone ="/assets/icons/Phone.svg"
images.amenities ="/assets/icons/amenities.svg"
images.building ="/assets/icons/buliding.svg"
images.calenderIcon ="/assets/icons/calendaricon.svg"
images.vectorIcon = "/assets/icons/vector.svg"
images.building = "/assets/icons/buliding2.svg"
images.construction ="/assets/icons/constructionicon.svg"
images.infoCircle = "/assets/icons/info-circle-icon.svg"
images.carousel = "/assets/icons/Carousel.svg"
images.projectInfo ="/assets/image/Projectinfo.png"
images.holdIcon = "/assets/icons/Hold.svg"
images.plusIcon = "/assets/icons/plus.svg"
images.datanullimg="/assets/icons/datanullimg.svg"
images.book = "/assets/icons/book.svg"
images.checkWIcon = "/assets/icons/check2-circle-white.svg"
images.infoWIcon = "/assets/icons/info-circle-white.svg"

export default images;
