export const commonConstants = {
  GLOBAL_RESET_TOAST_DATA: "GLOBAL_RESET_TOAST_DATA",
  GLOBAL_SET_TOAST_DATA: "GLOBAL_SET_TOAST_DATA",
  GLOBAL_LOADER_DATA: "GLOBAL_LOADER_DATA",

  FETCH_ALL_COMMON_ROLES_SAGA: "FETCH_ALL_COMMON_ROLES_SAGA",
  FETCH_ALL_COMMON_ROLES_SUCCESS: "FETCH_ALL_COMMON_ROLES_SUCCESS",
  FETCH_ALL_COMMON_ROLES_FAILURE: "FETCH_ALL_COMMON_ROLES_FAILURE",

  FETCH_COMMON_USER_LIST_SAGA : "FETCH_COMMON_USER_LIST_SAGA",
  FETCH_COMMON_USER_LIST_SUCCESS : "FETCH_COMMON_USER_LIST_SUCCESS",
  FETCH_COMMON_USER_LIST_FAILURE : "FETCH_COMMON_USER_LIST_FAILURE", 

  RESET_STATE : "RESET_STATE",
};
